// Code generated by MockGen. DO NOT EDIT.
// Source: internal/cmd/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/cmd/interfaces.go -destination=mocks/services.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	config "github.com/hurtki/configsManager/internal/config"
	domain "github.com/hurtki/configsManager/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAppConfigService is a mock of AppConfigService interface.
type MockAppConfigService struct {
	ctrl     *gomock.Controller
	recorder *MockAppConfigServiceMockRecorder
	isgomock struct{}
}

// MockAppConfigServiceMockRecorder is the mock recorder for MockAppConfigService.
type MockAppConfigServiceMockRecorder struct {
	mock *MockAppConfigService
}

// NewMockAppConfigService creates a new mock instance.
func NewMockAppConfigService(ctrl *gomock.Controller) *MockAppConfigService {
	mock := &MockAppConfigService{ctrl: ctrl}
	mock.recorder = &MockAppConfigServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppConfigService) EXPECT() *MockAppConfigServiceMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockAppConfigService) Load() (*config.AppConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load")
	ret0, _ := ret[0].(*config.AppConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockAppConfigServiceMockRecorder) Load() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockAppConfigService)(nil).Load))
}

// Save mocks base method.
func (m *MockAppConfigService) Save(arg0 *config.AppConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockAppConfigServiceMockRecorder) Save(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockAppConfigService)(nil).Save), arg0)
}

// MockConfigsListService is a mock of ConfigsListService interface.
type MockConfigsListService struct {
	ctrl     *gomock.Controller
	recorder *MockConfigsListServiceMockRecorder
	isgomock struct{}
}

// MockConfigsListServiceMockRecorder is the mock recorder for MockConfigsListService.
type MockConfigsListServiceMockRecorder struct {
	mock *MockConfigsListService
}

// NewMockConfigsListService creates a new mock instance.
func NewMockConfigsListService(ctrl *gomock.Controller) *MockConfigsListService {
	mock := &MockConfigsListService{ctrl: ctrl}
	mock.recorder = &MockConfigsListServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigsListService) EXPECT() *MockConfigsListServiceMockRecorder {
	return m.recorder
}

// GenerateUniqueKeyForPath mocks base method.
func (m *MockConfigsListService) GenerateUniqueKeyForPath(path string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateUniqueKeyForPath", path)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateUniqueKeyForPath indicates an expected call of GenerateUniqueKeyForPath.
func (mr *MockConfigsListServiceMockRecorder) GenerateUniqueKeyForPath(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateUniqueKeyForPath", reflect.TypeOf((*MockConfigsListService)(nil).GenerateUniqueKeyForPath), path)
}

// Load mocks base method.
func (m *MockConfigsListService) Load() (*domain.ConfigsList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load")
	ret0, _ := ret[0].(*domain.ConfigsList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockConfigsListServiceMockRecorder) Load() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockConfigsListService)(nil).Load))
}

// Save mocks base method.
func (m *MockConfigsListService) Save(arg0 *domain.ConfigsList) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockConfigsListServiceMockRecorder) Save(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockConfigsListService)(nil).Save), arg0)
}

// MockOsService is a mock of OsService interface.
type MockOsService struct {
	ctrl     *gomock.Controller
	recorder *MockOsServiceMockRecorder
	isgomock struct{}
}

// MockOsServiceMockRecorder is the mock recorder for MockOsService.
type MockOsServiceMockRecorder struct {
	mock *MockOsService
}

// NewMockOsService creates a new mock instance.
func NewMockOsService(ctrl *gomock.Controller) *MockOsService {
	mock := &MockOsService{ctrl: ctrl}
	mock.recorder = &MockOsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOsService) EXPECT() *MockOsServiceMockRecorder {
	return m.recorder
}

// FileExists mocks base method.
func (m *MockOsService) FileExists(path string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileExists", path)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FileExists indicates an expected call of FileExists.
func (mr *MockOsServiceMockRecorder) FileExists(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileExists", reflect.TypeOf((*MockOsService)(nil).FileExists), path)
}

// GetAbsolutePath mocks base method.
func (m *MockOsService) GetAbsolutePath(path string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAbsolutePath", path)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAbsolutePath indicates an expected call of GetAbsolutePath.
func (mr *MockOsServiceMockRecorder) GetAbsolutePath(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAbsolutePath", reflect.TypeOf((*MockOsService)(nil).GetAbsolutePath), path)
}

// GetFileData mocks base method.
func (m *MockOsService) GetFileData(path string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileData", path)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileData indicates an expected call of GetFileData.
func (mr *MockOsServiceMockRecorder) GetFileData(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileData", reflect.TypeOf((*MockOsService)(nil).GetFileData), path)
}

// GetHomeDir mocks base method.
func (m *MockOsService) GetHomeDir() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHomeDir")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHomeDir indicates an expected call of GetHomeDir.
func (mr *MockOsServiceMockRecorder) GetHomeDir() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHomeDir", reflect.TypeOf((*MockOsService)(nil).GetHomeDir))
}

// MakePathAndFile mocks base method.
func (m *MockOsService) MakePathAndFile(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakePathAndFile", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// MakePathAndFile indicates an expected call of MakePathAndFile.
func (mr *MockOsServiceMockRecorder) MakePathAndFile(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakePathAndFile", reflect.TypeOf((*MockOsService)(nil).MakePathAndFile), path)
}

// OpenInEditor mocks base method.
func (m *MockOsService) OpenInEditor(editor, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenInEditor", editor, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// OpenInEditor indicates an expected call of OpenInEditor.
func (mr *MockOsServiceMockRecorder) OpenInEditor(editor, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenInEditor", reflect.TypeOf((*MockOsService)(nil).OpenInEditor), editor, path)
}

// WriteFile mocks base method.
func (m *MockOsService) WriteFile(path string, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteFile", path, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteFile indicates an expected call of WriteFile.
func (mr *MockOsServiceMockRecorder) WriteFile(path, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteFile", reflect.TypeOf((*MockOsService)(nil).WriteFile), path, data)
}

// MockInputService is a mock of InputService interface.
type MockInputService struct {
	ctrl     *gomock.Controller
	recorder *MockInputServiceMockRecorder
	isgomock struct{}
}

// MockInputServiceMockRecorder is the mock recorder for MockInputService.
type MockInputServiceMockRecorder struct {
	mock *MockInputService
}

// NewMockInputService creates a new mock instance.
func NewMockInputService(ctrl *gomock.Controller) *MockInputService {
	mock := &MockInputService{ctrl: ctrl}
	mock.recorder = &MockInputServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInputService) EXPECT() *MockInputServiceMockRecorder {
	return m.recorder
}

// AskUser mocks base method.
func (m *MockInputService) AskUser(prompt string, options []string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AskUser", prompt, options)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AskUser indicates an expected call of AskUser.
func (mr *MockInputServiceMockRecorder) AskUser(prompt, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AskUser", reflect.TypeOf((*MockInputService)(nil).AskUser), prompt, options)
}

// GetPipedInput mocks base method.
func (m *MockInputService) GetPipedInput() (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPipedInput")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetPipedInput indicates an expected call of GetPipedInput.
func (mr *MockInputServiceMockRecorder) GetPipedInput() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPipedInput", reflect.TypeOf((*MockInputService)(nil).GetPipedInput))
}
