name: Go CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'  
          cache: false           

      - run: go env             

      # formating checking 
      - name: Check gofmt
        run: |
          if [ -n "$(gofmt -s -l .)" ]; then
            echo "Go files are not formatted. Run 'gofmt -s -w .' to fix."
            exit 1
          fi

      # Executing linter checking using golangci-lint
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.58.0
          args: run
          
      # Running tests
      - name: Run tests
        run: go test -v ./... --count=1
